### ISSUE TITLE
Image response schema

### ISSUE THREAD

**Issue by peyterkim** [fotinakis/swagger-blocks#105]
Is there support for `image/jpeg` responses? What is the syntax for the schema in a response?

**Comment by fotinakis** [comment]
Hey @peyterkim, sorry this is a Swagger question not a swagger-blocks question. Please see: https://github.com/fotinakis/swagger-blocks#filing-issues for other places you can get help.

**Comment by peyterkim** [comment]
is it a Swagger question if I'm specifically asking about swagger-block syntax?

From the swagger specification, I wrote this in swagger blocks:
`  /logo' do
    operation :get do
      key :summary, 'Get logo'
      key :tags, ['Logos']
      key :produces, ["image/jpeg"]
      response 200 do
        key :description, 'Successfully return a logo.'
        schema do
          key :type, :string
          key :format, :binary
        end
      end
    end
  end`
