### ISSUE TITLE
Setting host dynamically 

### ISSUE THREAD

**Issue by JCDJulian** [fotinakis/swagger-blocks#111]
One thing that would make swagger-blocks useful as a DSL would be the ability to interpolate variables as values.

Specifically, I want to set the host dynamically based on the root url. For example, on test, I want host to be 0.0.0.0:3000, and on prod I want it to be my production URL. I'd like to be able to get this from Rails through request.base_url, but it's not accessible from within the swagger_root block ( see error below). Is there any way to set the host dynamically based on environment?
`
undefined method `request' for #<Swagger::Blocks::Nodes::RootNode:0x007f7f501f9948>`

**Comment by biow0lf** [comment]
Try this:

```key :host, (ENV['SWAGGER_BLOCKS_HOST'] || 'localhost:3000')```

**Comment by prees1** [comment]
What if you want to set this via a variable?
