### ISSUE TITLE
Api::V1 module failing with Rails 5.2

### ISSUE THREAD

**Issue by pzupan** [fotinakis/swagger-blocks#112]
I've the following definition in Apidocs controller.
  ```
SWAGGERED_CLASSES = [
    Api::V1::RespondentsController,
    Respondent,
    ErrorModel,
    self,
  ].freeze
```
When I run  Swagger::Blocks.build_root_json(SWAGGERED_CLASSES) I get the following error:

`ArgumentError (A copy of Api::V1 has been removed from the module tree but is still active!)`

It works in Ruby 2.5 outside of Rails.  And I tried disabling Spring but that didn't help so it must be a conflict with the Rails development environment reloading.

**Comment by fotinakis** [comment]
Sorry, not sure how to help with this one as I don't think it's a swagger-blocks specific thing. Sounds like Rails autoloader is not figuring out the module paths correctly, you might be able to hint it with an explicit `require` or something.
