### ISSUE TITLE
Generate json files?

### ISSUE THREAD

**Issue by carlisia** [fotinakis/swagger-blocks#12]
Is there a desire to add the ability to generate json files with this gem? My thinking is that I'd like to aggregate multiple files from my separate microservices into one distinct app.

**Comment by fotinakis** [comment]
My thought is that it's pretty easy to write something to do this yourself so I haven't added explicit support for writing files. You could easily do something like:

```Ruby
swagger_data = Swagger::Blocks.build_root_json(SWAGGERED_CLASSES)
File.open(path, 'w') { |file| file.write(swagger_data.to_json) }
```

For aggregating across services part, I'm not sure what the best Swagger-capable thing is to do there. I guess you could grab these files from each microservice, deserialize them and then combine the generated data—could work if you to merge them correctly and they have the same root information.

Feel free to re-open or comment with more thoughts.

**Comment by carlisia** [comment]
@fotinakis thank you for such a prompt and useful reply re: fetching the generated json and writing it to a file.

I did a sweep of the intertubes and found out that the Swagger team is working on extending the specs to allow for multiple microservices api documentation. I annotated my findings here: http://stackoverflow.com/questions/23296723/swagger-ui-for-multiple-restful-services/29145659#29145659. I'm surprised that I don't find more people looking for a solution to this issue.

**Comment by fotinakis** [comment]
:+1:

**Comment by fotinakis** [comment]
I've also updated the docs with a small note about writing the swagger JSON to a file:
https://github.com/fotinakis/swagger-blocks/blob/master/README.md#writing-json-to-a-file

**Comment by carlisia** [comment]
:+1:
