### ISSUE TITLE
Array of schema inside another schema

### ISSUE THREAD

**Issue by rhazegh** [fotinakis/swagger-blocks#17]
I want to define a swagger schema/model for `Book` that has and array of chapters inside. I want the following JSON:

```json
{
  "name": "string",
  "num_pages": 0,
  "chapters": [
    {
      "title": "string",
      "text": "string"
    }
  ]
}
```
So I defined the following two swagger schemas:

```ruby
  swagger_schema :Chapter do
    property :title do
      key :type, :string
    end
    property :text do
      key :type, :string
    end
  end
```

```ruby
  swagger_schema :Book do
    property :name do
      key :type, :string
    end
    property :num_pages do
      key :type, :integer
      key :format, :int64
    end
    property :chapters do
      key :'$ref', :Chapter
      key :type, :array
    end
  end
```

But I end up getting the following in the generated swagger documentation for `Book`:
```json
{
  "name": "string",
  "num_pages": 0,
  "chapters": 
    {
      "title": "string",
      "text": "string"
    }
}
```

What is the proper way to define an array of a schema inside another schema?

**Comment by fotinakis** [comment]
The keys are case-sensitve, can you try `:Chapter` instead of `:chapter`?

**Comment by rhazegh** [comment]
My bad. I corrected the typos I made above. I just fabricated the above example to describe the problem I am having. My real models have so many properties and the capitalization is correct on the actual models.

**Comment by fotinakis** [comment]
Also, in Swagger JSON I believe you _must_ use an `items` definition if you use the `array` type anywhere.

**Comment by rhazegh** [comment]
yes, I tries to use `items` later, but what is the swagger-blocks syntax for it?

**Comment by fotinakis** [comment]
I just added an [example](https://github.com/fotinakis/swagger-blocks/commit/e7e251b06b1299cad66eed8e247c3af2148813c6) for arrays in schema objects. So you would do something like:

```ruby
    property :chapters do
      key :type, :array
      items do
        key :'$ref', :Chapter
      end
    end
```

Let me know if that works.

**Comment by rhazegh** [comment]
Yes it works :+1:   Thank you :smiley:

**Comment by ayadavkrt** [comment]
```
property :something do
      key :type, :array
      items do
        key :'$ref', :Chapter
        key :'$ref', :Disaster
        key :'$ref', :Creator
      end
    end
```

How can one do this ???
