### ISSUE TITLE
Nested object responses?

### ISSUE THREAD

**Issue by elsurudo** [fotinakis/swagger-blocks#20]
I wasn't able to figure out how to specify a response of a more complex object (ie. not just one "level" of key-value pairs).

Is this possible? If so, perhaps there should be an example of this in the README.

What I mean is representing something like:
```
{
  "error": {
    "code": "not_found",
    "message":"Resource not found"  
  }
}
```
with the `schema do`syntax

**Comment by fotinakis** [comment]
You can give whatever you want to `key` and it will be put directly into the final JSON object, so you can do:

```ruby
key :foo, {bar: 123, baz: 234}
```

Does that work for your case?

**Comment by elsurudo** [comment]
Right, but in that case we've stepped out of the block format, and I can't specify which type of variable the value for key `bar` will be, etc., and just pass an "example response". Unless I misunderstand something?

**Comment by elsurudo** [comment]
Ah, I guess whatever is the second argument there is actually supposed to be a JSON schema, so I'd have to be a bit more verbose to specify things.

**Comment by fotinakis** [comment]
Oh I see — yeah it's a JSON Schema object, which apparently does support nested types: http://json-schema.org/latest/json-schema-core.html#rfc.section.3.4

Can you try to just create the JSON manually (or manually with `key`) and let me know if Swagger UI correctly understands nested schemas? If it does, I can put it on the roadmap to support nesting `swagger_schema` inside of `swagger_schema` in swagger-blocks.

**Comment by elsurudo** [comment]
Honestly, my version of Swagger UI (master HEAD) doesn’t even seem to understand the non-nested schemas being spit out by swagger-blocks (the returned model section is simply empty). I’m new to swagger myself, so I can’t yet tell where the issue lies.

I will try to find out if I can.

**Comment by fotinakis** [comment]
@elsurudo did you figure out if nested schemas are supported by Swagger UI?

**Comment by elsurudo** [comment]
Not yet, Mike. I’m actually off this week, so haven’t had the time to look into it. Next week :)

**Comment by sirwolfgang** [comment]
I got it to work with this:

```ruby
swagger_schema :Item do
  property :id do
    key :type, :string
  end

  property :status do
    key :type, :object
    key :properties, {
      message: {
        type: 'string'
      },
      timestamp: {
        type: 'string'
      }
    }
  end
end
```

**Comment by sirwolfgang** [comment]
With that in mind it would be nice to get a syntax more like:
```ruby
property :status do
  object do
    property :message do
      key :type, :string
    end
    property :timestamp do
      key :type, :string
    end
  end
end
```

or

```ruby
property :status, type: :object do
  property :message do
    key :type, :string
  end
  property :timestamp do
    key :type, :string
  end
end
```

**Comment by atistler** [comment]
+1

**Comment by Yoshyn** [comment]
+1

**Comment by Yoshyn** [comment]
If someone is interested, here are the monkey-patch i use. It allow the two syntax defined by @sirwolfgang 
Moreover, you can write : 
```ruby
property :field, type: :my_type
```
which is a shortcut for 
```ruby
property :field do
  key :type, :my_type
end
```

You can put it in an initializer :
```ruby 
module Swagger
  module Blocks
    class PropertiesNode < Node
      def property(name, type: nil, &block)
        if block_given? && type.to_s == 'object'
          self.data[name] = Swagger::Blocks::PropertyNode.new
          self.data[name].version = version
          self.data[name].object(&block)
        else
          block = Proc.new { key(:type, type) } if type

          self.data[name] = Swagger::Blocks::PropertyNode.call(version: version, &block)
          self.data[name]
        end
      end
    end

    class PropertyNode < Node
      def object(&block)
        key(:type, :object)
        self.data[:properties] ||= Swagger::Blocks::PropertiesNode.call(version: version, &block)
      end
    end

    class SchemaNode < Node
      def property(name, type: nil, &block)
        self.data[:properties] ||= Swagger::Blocks::PropertiesNode.new
        self.data[:properties].version = version
        self.data[:properties].property(name, type: type, &block)
      end
    end
  end
end
```

**Comment by fotinakis** [comment]
Closing this old issue due to inactivity.

**Comment by maurodias** [comment]
@elsurudo 
I don't know if I misunderstood you but wasn't these [dictionaries/hashmaps](https://swagger.io/docs/specification/data-models/dictionaries/) what you want in swagger-blocks?
