### ISSUE TITLE
[Question] Dynamic query parameters

### ISSUE THREAD

**Issue by rhazegh** [fotinakis/swagger-blocks#21]
I am using Ransack (https://github.com/activerecord-hackery/ransack/wiki/Basic-Searching) to build dynamic queries.

Say I have this model:
```
first_name: string
last_name: string
age: integer
email: string
```

Is there any way to document the following query? 
`GET api/v1/users?q[first_name_cont]=eric&q[email_not_cont]=gmail`

or this?
`GET api/v1/users?q[last_name_cont]=johnson&q[age_gt]=18&q[email_cont]=gmail`

If not, do you know any workarounds for this?

**Comment by fotinakis** [comment]
Not sure exactly, what have you tried? This may be more of a swagger related question than an issue with swagger-blocks itself. My old comment here might be related: https://github.com/fotinakis/swagger-blocks/issues/4#issuecomment-70575007

**Comment by rhazegh** [comment]
I decided to provide an alternative format for submitting queries and am using that alternative format in Swagger.

**original Format:** `GET api/v1/users?q[first_name_cont]=eric&q[email_not_cont]=gmail`

**alternative format:** `GET api/v1/users?q={"first_name_cont": "eric", "email_not_cont": "gmail"}`

**Comment by fotinakis** [comment]
I think you could get either to work and be documented correctly, but the first one is more HTTP-standard. Going to close this for now since this isn't really swagger-blocks related, but feel free to comment if you find that swagger-blocks cannot correctly create Swagger JSON in the format you want.

**Comment by rhazegh** [comment]
As you mentioned, it's a swagger issue. I think they do not support the format that I need in the specification.
