### ISSUE TITLE
Any thing about generating json file for UI?

### ISSUE THREAD

**Issue by matt-hu** [fotinakis/swagger-blocks#25]
how to generate json file for ui? In swagger-docs, we run 'rake swagger:docs', so in swagger-blocks, how should we prepare these files for front-end.

**Comment by matt-hu** [comment]
please ignore my naive and carelessness

**Comment by fotinakis** [comment]
Haha, glad you figured it out. :)

**Comment by vishaltps** [comment]
@fotinakis  I have same question. can you explain me ?
