### ISSUE TITLE
is it possible to reorder the endpoints in a tag

### ISSUE THREAD

**Issue by matt-hu** [fotinakis/swagger-blocks#26]
I like to order endpoints by "GET",''POST","PUT","PATCH","DELETE", I didn't find any documentation in README, is it possible to order like that.

**Comment by matt-hu** [comment]
<img width="669" alt="2015-07-23 16 32 42" src="https://cloud.githubusercontent.com/assets/5038636/8846301/7e7a0302-3158-11e5-8522-23f9602c57e0.png">
something like this.

**Comment by fotinakis** [comment]
Sorry, I don't know the answer—this is a question about [swagger-ui](https://github.com/swagger-api/swagger-ui) or the [swagger-spec](https://github.com/swagger-api/swagger-spec) itself, not about swagger-blocks.
