### ISSUE TITLE
Selectable related objects

### ISSUE THREAD

**Issue by mojidabckuu** [fotinakis/swagger-blocks#33]
I read doc for version 2.0 and find enum filed with empty doc. Does it mean that enum is not ready or I missed something?

**Comment by fotinakis** [comment]
Have you tried this?

```
key :enum, ['foo', 'bar']
```

**Comment by mojidabckuu** [comment]
@fotinakis yes in that way it works, but is it possible to setup in the way ['foo' => 1, 'bar' => '2'] to show in API, for example country name, but when request is sent in params obtain id of 1,2,...,n ?

**Comment by fotinakis** [comment]
An enum is always a list, you could put `{foo: 1}` there but I don't think it's valid according to swagger. You'd need to translate the name to the ID on your backend, or use a datastructure that is not an enum. Closing this issue now since we do support `enum` in this swagger-blocks gem.
