### ISSUE TITLE
Need help: Wrap object in key when posting data

### ISSUE THREAD

**Issue by titzi** [fotinakis/swagger-blocks#35]
Hi,

I need help with a problem I'm currently dealing with. I want to use Swagger UI and send the data in a POST request wrapped in an object key and don't know how to do this. I already tried several things but it looks like I'm not clever enough.

Here is a simplified version of my Swagger Blocks code:

```javascript
swagger_path '/users' do
  operation :post do
    key :operationId, 'createUser'
    parameter do
      key :name, :user
      key :in, :body
      key :required, true
      schema do
        key :'$ref', :UserInput
      end
    end
  end
end

swagger_schema :UserInput do
  key :required, [:name]
  property :name do
    key :description, "Name of the User"
    key :type, :string
  end
end
```

The Swagger UI tries to send a POST request with parameters in the body:
```
curl -X POST -d "{\"name\": \"string\"}" http://whatever.com/
```

What I need is something like this, sending the body parameters wrapped in a key:
```
curl -X POST -d "{\"user\":{\"name\": \"string\"}}" http://whatever.com/
```

Is something like that possible using swagger blocks options? 

Thanks for your help!

Alex

**Comment by fotinakis** [comment]
Hey! Sorry, this is a question about Swagger and Swagger UI, so this isn't the right place for it. If you find that Swagger supports what you are trying to do, but that swagger-blocks can't build the right structure, that would be a bug, but otherwise please see: https://github.com/fotinakis/swagger-blocks#filing-issues
