### ISSUE TITLE
How can i use versionist and unable lo UI

### ISSUE THREAD

**Issue by ranjithnalimela** [fotinakis/swagger-blocks#36]
My application have versionist (i.e version 1, 2 ,3...). How can i user swagger-block with version management and swagger UI Not loading it shows only json response.

 gem 'swagger-blocks'
gem 'versionist' 
https://github.com/bploetz/versionist

https://github.com/fotinakis/swagger-blocks

class ApidocsController < ApplicationController
  include Swagger::Blocks
 swagger_root do
    key :swagger, '2.0'
    info do
      key :version, '1.0.0'
    end
end
SWAGGERED_CLASSES = [
    Api::V1::RestaurantsController,
    self,
  ].freeze

  def index
    render json: Swagger::Blocks.build_root_json(SWAGGERED_CLASSES)
  end
end

**Comment by fotinakis** [comment]
You have to point swagger UI at the JSON endpoint, I believe it's a text box in swagger UI.

As for versioning, my recommendation is to do something inside of the `index` method—figure out which version of the API was requested, and serve a different set of swaggered classes.
