### ISSUE TITLE
unable to get v1.2 of the docs to work fully

### ISSUE THREAD

**Issue by jonheckman** [fotinakis/swagger-blocks#37]
I am currently working to switch from using https://github.com/richhollis/swagger-docs to swagger-blocks.
Right now my plan is to use swagger docs for the original version of my API and use swagger-blocks for anything new, upgrade swagger to 2.0 when I deprecate the old version of my API.
A lot of the data below is directly copied from the documentation, I wanted to get that working than modify it to match my needs.
Relevant files:
/app/controllers/api/v2/items_controller.rb
```
class Api::V2::ItemsController < Api::ApiController
  before_action :authenticate

  after_action :log_usage

  swagger_path '/items/{id}' do
    operation :get do
      key :description, 'Returns a single pet if the user has access'
      key :operationId, 'findPetById'
      key :tags, [
        'pet'
      ]
      parameter do
        key :name, :id
        key :in, :path
        key :description, 'ID of pet to fetch'
        key :required, true
        key :type, :integer
        key :format, :int64
      end
      response 200 do
        key :description, 'pet response'
        schema do
          key :'$ref', :Pet
        end
      end
      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end
    end
  end
```
app/controllers/newapidocs_controller.rb (I did newapidocs since the swagger-docs gem was already using /apidocs)
```
class NewapidocsController < ApplicationController
  include Swagger::Blocks
  swagger_root do
    key :swaggerVersion, '1.2'
    key :apiVersion, '2.0.0'
     info do
       key :title, 'my site'
       key :description, 'api'
       key :termsOfService, ''
       key :name, 'email'
     end
     api do
      key :path, '/items'
      key :description, 'Operations about pets'
     end
     key :host, 'localhost:3000'
     key :basePath, '/api/v2'
     key :consumes, ['application/json']
     key :produces, ['application/json']
   end

   # A list of all classes that have swagger_* declarations.
   SWAGGERED_CLASSES = [
     ItemsController,
     self,
   ].freeze

  def index
    render json: Swagger::Blocks.build_root_json(SWAGGERED_CLASSES)
  end

  def show
    render json: Swagger::Blocks.build_api_json(params[:id], SWAGGERED_CLASSES)
  end
end
```
routes
```
  namespace :api, defaults: {format: 'json'} do
    namespace :v2 do
      resources :items
      resources :craftings
    end
  end
```
With this I am able to point swagger-ui correctly to /newapidocs and that at least partially loads.
I have a row for 'items', however it cannot read the item information.
I am getting `Unable to read api 'items' from path /api/v2/items (server returned undefined)`

I feel like I am missing something very obvious but I can't figure out what it is.
Not sure what other information I can give. 

Edit:
I have made some progress in diagnosing this issue.
I removed the line `key :basePath, '/api/v2'` from the apidocs controller. Doing this made the docs themselves load how I wanted them to but "try it out" did not call the right location.
Instead of doing "/api/v2/items" it was doing "/newapidocs/v2/items"

**Comment by fotinakis** [comment]
Closing old issue.
