### ISSUE TITLE
Unable to specify an array as the value of a body parameter

### ISSUE THREAD

**Issue by number61971** [fotinakis/swagger-blocks#38]
I am trying to specify an array as a body parameter to a PUT request. The Swagger API seems to allow this, but when trying to make this work using swagger-blocks, Rails throws a 500.

For example, given the following API route:

    api do
      key :path, '/contributions/bulk_submit'
      key :description, 'Efficiently submit a bunch of contributions by ID'
      operation do
        key :method, 'PUT'
        key :summary, 'Submits all the specified contributions'
        key :nickname, :Contributions_BulkSubmit
        parameter do
          key :paramType, :body
          key :name, :contribution_ids
          key :description, 'An array of the individual contribution IDs being submitted'
          key :required, true
          key :type, :ArrayContributionSubmitPayload
        end
        response_message do
          key :code, 200
          key :message, 'Success.'
        end
      end
    end

I'd like the `:ArrayContributionsSubmitPayload` to look like this:
    
    swagger_model :ArrayContributionSubmitPayload do
      key :id, :ArrayContributionSubmitPayload
      key :type, :array
      items do
        key :type, :integer
      end
    end

or possibly this:
    
    swagger_model :ArrayContributionSubmitPayload do
      key :id, :ArrayContributionSubmitPayload
      schema do
        key :type, :array
        items do
          key :type, :integer
        end
      end
    end

However, neither option works. The only way I can specify an array in the body parameter is to further encapsulate it like so:
    
    swagger_model :ArrayContributionSubmitPayload do
      key :id, :ArrayContributionSubmitPayload
      property :contribution_ids do
        key :type, :array
        items do
          key :type, :integer
        end
      end
    end

But that results in documentation that leads the end user to believe that you have to name a `contribution_ids` parameter, and that parameter takes a JSON payload that specifies an object that looks like this:

    {contribution_ids: [0, 1, ...]}

Which is WRONG.

Rather, the end users specifies a `contribution_ids` parameter, and that parameter is a JSON array, like this:

    [0, 1, ...]

After much research, I believe that this should be possible, but that for some reason swagger-blocks does not support it, and thus must be a bug.

**Comment by fotinakis** [comment]
Check out my comment here from a while back, I think it might answer your question:
https://github.com/fotinakis/swagger-blocks/issues/4#issuecomment-70575007

Please re-open if I'm wrong and you're talking about something else. :)

**Comment by number61971** [comment]
That doesn't help. Let me post you links to 2 screenshots that illustrate the problem.

<img width="975" alt="swagger" src="https://cloud.githubusercontent.com/assets/1045385/12585651/97d297b8-c412-11e5-8c65-8bd528ce2372.png">

In that screenshot, you can see the "contributions" body parameter taking an object with a key of "contributions", which is associated with an array of objects. I.e., the documentation makes it look like this is what the body payload for the endpoint is:

    {
      contributions: {
        contributions: [
          {id: 0, name: 'whatever', ...},
          {id: 1, name: 'blah', ...}
        ]
      }
    }

Which is WRONG. What I want is to produce documentation that looks like this:

<img width="969" alt="swagger_what_i_want" src="https://cloud.githubusercontent.com/assets/1045385/12585742/f8bee298-c412-11e5-879a-779d31358b53.png">

In that pic, you can see that the swagger docs make it look like the body payload should be as follows:

    {
      contributions: [
        {id: 0, name: "something", ...},
        {id: 1, name: "blah", ...}
      ]
    }

THAT is correct! And also what I want the swagger docs to generate. But I can't seem to make that happen.

**Comment by number61971** [comment]
Hi, Mike,

I posted an update three days ago to help clarify the issue I'm having.
Hoping you've had a chance to look at it. I allow that I could be missing
something very obvious, but otherwise I do believe there is a genuine bug
that needs to be fixed.

Best regards,
~Damon

**Comment by fotinakis** [comment]
Yes I saw, I've been too busy to dig in at the moment. I'll have a chance to look again tomorrow.

**Comment by fotinakis** [comment]
I think your problem is that you're not using the `key :'$ref'` feature to reference the model.

For example:
See here for the `key :'$ref'` usage to reference a model in a POST request. https://github.com/fotinakis/swagger-blocks/blob/v1.2.0/spec/lib/swagger_v2_blocks_spec.rb#L100
See here for how to use the `$ref` feature with an array:
https://github.com/fotinakis/swagger-blocks/blob/v1.2.0/spec/lib/swagger_v2_blocks_spec.rb#L86
```ruby
        schema do
          key :type, :array
          items do
            key :'$ref', :Pet
          end
        end
```

I believe this is supported by swagger-blocks and by Swagger (see the [createUsersWithArrayInput](http://petstore.swagger.io/#!/user/) example). If you find that swagger-blocks cannot support the Swagger feature please re-open this issue, but I think this is just a matter of digging further in to figure out the correct Swagger format. You can try changing the underlying Swagger JSON manually until you get Swagger UI to be what you want, then see if you can replicate that inside swagger-blocks.

**Comment by number61971** [comment]
We're using both arrays and $ref in other parts of our documentation. And when employed as you point out in your examples, it does indeed work. With the exception of trying to specify an array as the value of a body parameter. That's why we find this so difficult to understand. In every other context, e.g., in responses, everything works as advertised. But the exact same syntax employed in those other contexts simply does not work when employed in association with a body parameter.

**Comment by fotinakis** [comment]
Interesting. Your original example shows this:
```ruby
api do
  key :path, '/contributions/bulk_submit'
  key :description, 'Efficiently submit a bunch of contributions by ID'
  operation do
    key :method, 'PUT'
    key :summary, 'Submits all the specified contributions'
    key :nickname, :Contributions_BulkSubmit
    parameter do
      key :paramType, :body
      key :name, :contribution_ids
      key :description, 'An array of the individual contribution IDs being submitted'
      key :required, true
      key :type, :ArrayContributionSubmitPayload
    end
    response_message do
      key :code, 200
      key :message, 'Success.'
    end
  end
end
```

You're saying that this doesn't work?
```ruby
api do
  key :path, '/contributions/bulk_submit'
  key :description, 'Efficiently submit a bunch of contributions by ID'
  operation do
    key :method, 'PUT'
    key :summary, 'Submits all the specified contributions'
    key :nickname, :Contributions_BulkSubmit
    parameter do
      key :paramType, :body
      key :description, 'An array of the individual contribution IDs being submitted'
      key :required, true
      key :type, :array
      items do
        key :'$ref', :ArrayContributionSubmitPayload
      end
    end
    response_message do
      key :code, 200
      key :message, 'Success.'
    end
  end
end
```
Removed `key :name, :contribution_ids`, and added:
```
      key :type, :array
      items do
        key :'$ref', :ArrayContributionSubmitPayload
      end
```
