### ISSUE TITLE
How do I load the UI from the rails app

### ISSUE THREAD

**Issue by ashramsey** [fotinakis/swagger-blocks#45]
I've followed the readme, and I only get back the json blob in the browser. Do I need to use another gem for displaying the UI? Or is there some other part to this picture I'm missing? 

Thanks

**Comment by fotinakis** [comment]
You're missing Swagger UI, which is a totally separate thing. Unfortunately, I can't provide any support for getting that set up, see: https://github.com/fotinakis/swagger-blocks#filing-issues
