### ISSUE TITLE
Swagger not setting Authorization header for Oauth2.

### ISSUE THREAD

**Issue by TurtleShip** [fotinakis/swagger-blocks#46]
Hi, apologies in advance if this has been a known issue and I am re-reporting this. I spent a good part of today trying to find a solution to my current problem and was unable to.

I am developing an app that uses token based oauth, using [devise_token_oauth gem](https://github.com/lynndylanhurley/devise_token_auth). I specified my swagger security definition as below

```ruby
security_definition :devise_auth do
      key :type, :oauth2
      key :authorizationUrl, '/api/doc/auth'
      key :flow, :implicit
      key :tokenName, 'access-token'

      scopes do
        key 'god', 'God can do everything'
        key 'lecturer', 'Lecturer can create courses'
      end
    end
```

And I also defined swagger_path to use the security definition as below
```ruby
 swagger_path '/api/schools' do
    operation :post do
      key :description, 'Creates a school. Only users with God permission can operate.'
      key :tags, [:school]

      security do
        key :api_key, []
      end

      security do
        key :devise_auth, ['god']
      end

      parameter do
        key :name, :school
       ...
      end
end
```

I defined api/doc/auth endpoint so that it returns all header information in query param. For example, it returns the below url
```
 http://localhost:3000/swagger-ui/dist/o2c.html?access-token=1FzOVl6NmBqEtycXnRIeUg&token-type=Bearer&client=EpUPSWWVbWPO2OkQG4Imng&expiry=1459736879&uid=god@gmail.com
```
It has ```access-token, token-type, client, expiry, uid```, all of which the Swagger needs to send to my API server to authenticate. 

When I go to Swagger doc, I correctly see a toggle that asks me if I want to enable Oauth.
<img width="986" alt="screen shot 2016-03-20 at 7 40 21 pm" src="https://cloud.githubusercontent.com/assets/3166423/13909641/f6458db4-eed3-11e5-9cfe-94608be9b532.png">
<img width="653" alt="screen shot 2016-03-20 at 7 40 26 pm" src="https://cloud.githubusercontent.com/assets/3166423/13909648/ffdaea40-eed3-11e5-9d51-521183714c13.png">

When I click it, the toggle correctly turn to "On".
<img width="981" alt="screen shot 2016-03-20 at 7 40 38 pm" src="https://cloud.githubusercontent.com/assets/3166423/13909649/036f3eae-eed4-11e5-94d0-aa278bffb401.png">

However, when I send a request, I do not see auth header values ...
<img width="956" alt="missing_auth" src="https://cloud.githubusercontent.com/assets/3166423/13909659/2d2da726-eed4-11e5-8edb-e728df76f59a.png">

What am I doing wrong?
How can I tell Swagger doc that it needs to use auth params it got back from the AuthorizationUrl endpoint? Or is this type of question more appropriate for swagger-ui repo? I will keep this question until told otherwise.

 Thanks in advance!

**Comment by fotinakis** [comment]
Sorry nothing jumps out at me as what is wrong here. This is more for swagger UI or http://swagger.io/community/.

**Comment by Aveline67** [comment]
I can easily reproduce this issue ! Very frustrating....
