### ISSUE TITLE
Are type definitions supported?

### ISSUE THREAD

**Issue by dapicester** [fotinakis/swagger-blocks#48]
Swagger 2 uses [definitions](http://swagger.io/specification/#definitionsObject) to describe parameter/property type. 

I tried adding a `definition` block in `swagger_root` for the example in the specification link:
```ruby
definition :Category do
  key :type, :object
  property :id, type: :integer, format: 'int64'
  property :name, type: :string
end
```
 but I got:
```
undefined method `definition' for #<Swagger::Blocks::RootNode:0x007f6b50f0b668>
```

I am using the gem version 1.3.2

**Comment by gogiel** [comment]
You are probably looking for [swagger_schema](https://github.com/fotinakis/swagger-blocks/blob/master/lib/swagger/blocks.rb#L174-L188) method.

**Comment by fotinakis** [comment]
Yes, what @gogiel said. We could consider aliasing that method.
