### ISSUE TITLE
PathNode level parameter declaration

### ISSUE THREAD

**Issue by johnideal** [fotinakis/swagger-blocks#49]
[According to the docs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object), I would expect swagger-blocks to support PathNode-level parameter declarations. I'd be happy to contribute to support this, but I wanted to make sure that I'm not missing something?

**Comment by fotinakis** [comment]
I think you're probably missing it in the docs: https://github.com/fotinakis/swagger-blocks#petscontroller
See the `parameter` calls.

**Comment by johnideal** [comment]
I see operation level usage; not path level usage.

**Comment by fotinakis** [comment]
Yup, looks like you're right, this should be supported but is not. It should be relatively simple to add, just need to add a `parameter` method to the `PathNode` class and update the tests. Feel like taking this on? Happy to accept a PR for it.

**Comment by johnideal** [comment]
Yup, I'll give it a go. Thanks!
