### ISSUE TITLE
Override API authorizations at the operation level (to nil)

### ISSUE THREAD

**Issue by claude** [fotinakis/swagger-blocks#5]
OK, I think I may finally have legitimate feature request :smile: 

According to the swagger spec, section 5.2.3 - the Operation object authorizations parameter: 

> A list of authorizations required to execute this operation. While not mandatory, if used, it overrides the value given at the API Declaration's authorizations. In order to completely remove API Declaration's authorizations completely, an empty object ({}) may be applied.

So most of my API requires authorization, but a few endpoints do not. So I'd like to just clear out the authorization on those endpoints by setting authorizations to the empty object {}. I don't see a way to do that with swagger blocks, or is there?

**Comment by fotinakis** [comment]
Almost @claude! You can use the standard `key` method to set anything you'd like, so you can simply do this:

```ruby
operation do
  key :authorizations, {}
  # ...
end
```

Which produces JSON like: `"operations":[{"authorizations":{},...` which matches what the swagger spec is asking for. :)

**Comment by claude** [comment]
ha! great thanks! Was that somewhere in the readme or the spec and I missed it?

**Comment by fotinakis** [comment]
I don't think it is, just a feature of how `key` is implemented. I'll add something to the README.
