### ISSUE TITLE
externalDocs block does not work in swagger_root

### ISSUE THREAD

**Issue by dapicester** [fotinakis/swagger-blocks#51]
Adding the `externalDocs` block in the `swagger_root` causes an error:

```
ActionController::RoutingError (undefined method `externalDocs' for #<Swagger::Blocks::RootNode:0x000000071f2550>)
```

but it works fine if used within a `tag` block.

I believe it should be allowed in the root block because I see it in the [specs](http://swagger.io/specification/#swaggerObject).

**Comment by fotinakis** [comment]
I think you're right! Happy to accept a PR for this if you're up for it, it should be pretty easy to add and add a test for. See this recent PR for an example: https://github.com/fotinakis/swagger-blocks/pull/50/files — If you're not up for it, I can take it on at some point.
