### ISSUE TITLE
ApidocsController#index returning "failed to parse JSON/YAML response"

### ISSUE THREAD

**Issue by peyterkim** [fotinakis/swagger-blocks#53]
I believe I have everything set up correctly, but when I go to the `/apidocs` endpoint, it serves me json rather than Swagger UI.

ApidocsController:
```
class ApidocsController < ActionController::Base
  include Swagger::Blocks

  swagger_root do
    key :swagger, '2.0'
    info do
      key :version, '3.0'
      key :title, 'My API'
      key :description, "The latest version of API"
    end
    key :host, 'localhost:3000'
    key :basePath, '/api/v3'
    key :consumes, ['application/json']
    key :produces, ['application/json']
  end

  # A list of all classes that have swagger_* declarations.
  SWAGGERED_CLASSES = [
    Api::V3::UsersController,
    User,
    self,
  ].freeze

  def index
    render json: Swagger::Blocks.build_root_json(SWAGGERED_CLASSES)
  end
end
```

route.rb:
`resources :apidocs, only: [:index]`

public/apidocs/index.html for Swagger UI:
```
window.swaggerUi = new SwaggerUi({
  url: '/apidocs',
  ...
});
```

the result:
<img width="1155" alt="screen shot 2016-04-23 at 12 06 50 pm" src="https://cloud.githubusercontent.com/assets/5760340/14762580/e43d0dd0-094b-11e6-8c55-d2fbe8056f04.png">

**Comment by peyterkim** [comment]
nvm, got it to work!

**Comment by fotinakis** [comment]
@peyterkim Can you share the solution for others who might stumble on this issue? If it's simple.

**Comment by vishaltps** [comment]
@peyterkim Yes i am stuck at this point . can you tell me the solution
 ?
