### ISSUE TITLE
Swagger UI integration with swagger-blocks is confusing

### ISSUE THREAD

**Issue by peyterkim** [fotinakis/swagger-blocks#54]
Is there any way you could add more complete documentation for how to handle the Swagger UI side of things? It seems like that is the part that is missing from the instructions. The fact that it's an integral part of getting all this to work, it's crucial information. Specifically, expanding on your set up of Swagger UI and what you mean by "point Swagger UI to /apidocs and everything should just work."

**Comment by peyterkim** [comment]
nvm, got it to work!

**Comment by ericpeters0n** [comment]
Agree: still confusing.

**Comment by fotinakis** [comment]
How can it be made clearer? I'm happy to accept PRs for README updates to make this clearer for people getting set up, while keeping in mind that swagger-blocks here is an unoffical third-party library, and Swagger UI is an official first-party library (so it's out of scope to include the whole Swagger UI setup process here, but integration hints would be great).

**Comment by seanfcarroll** [comment]
I'm on board with it being confusing. I've followed the README and now have the Swagger-format json being generated. Now what? I guess I need to set up another server for Swagger?

**Comment by biow0lf** [comment]
@seanfcarroll for example:

```shell
cd public
git clone https://github.com/swagger-api/swagger-ui.git
cd swagger-ui/
git checkout v2.2.10
```
Change url = `http://petstore.swagger.io/v2/swagger.json`; to url = `http://localhost:3000/api/docs.json`; in public/dist/index.html

Where `/api/docs.json` path to your swagger-blocks endpoint.

Open `http://localhost:3000/dist/index.html` in browser.

**Comment by seanfcarroll** [comment]
hi @biow0lf that's great, thank you. I also found a project that mounts it as a Rails engine: https://github.com/batdevis/swagger_engine

**Comment by gaukharaya** [comment]
@seanfcarroll do you mind explaining how you integrated swagger engine with swagger ui please?

**Comment by quarryman** [comment]
@biow0lf
> Change url = http://petstore.swagger.io/v2/swagger.json; to url = http://localhost:3000/api/docs.json; in public/dist/index.html

No need to change dist/index.html
It accepts 'url' param which specifies swagger generated json url, rails endpoint in case one followed this repo manual for mounting swagger controller to 'apidocs' route of your app.

`http://localhost:3000/dist/index.html?url=http://localhost/apidocs`

**Comment by belgoros** [comment]
@biow0lf Just one question, - in what file should the below change be done:

> Change url = http://petstore.swagger.io/v2/swagger.json; to url = http://localhost:3000/api/docs.json; in public/dist/index.html

Thank you.

**Comment by belgoros** [comment]
@quarryman I don't know how you can have 2 servers run on the same host and port (`localhost:3000`). Either one need to precise that swagger-ui server should be started and point out the way to do that or it just does not work when you start you rails server in dev mode as usual with `rails s`, because there is no route to `[GET] "/dist/index.html`:
<img width="432" alt="screenshot 2018-12-05 at 11 04 29" src="https://user-images.githubusercontent.com/83579/49506122-90e00100-f87d-11e8-8ee4-2f312af4285b.png">
