### ISSUE TITLE
Can a model schema's property be an association object?

### ISSUE THREAD

**Issue by peyterkim** [fotinakis/swagger-blocks#55]
For example:

`user.rb`
```
swagger_schema :User do
  property :name, type: :string
  property :school do
    key :'$ref', :School
  end
end
```

`school.rb`
```
swagger_schema :School do
  property :name, type: :string
  property :district, type: :string
end
```

**Comment by fotinakis** [comment]
Sorry @peyterkim, this is a Swagger question, not a Swagger Blocks question. Please see: https://github.com/fotinakis/swagger-blocks#filing-issues

**Comment by CBarraford** [comment]
@peyterkim did you find the answer to your question? Trying to answer it for myself at the moment.

**Comment by alexandru-calinoiu** [comment]
@CBarraford 1 year later :)

```
      property :model, schema: { :"$ref" => :Model }, required: true
```
