### ISSUE TITLE
Reference parameters at operation level

### ISSUE THREAD

**Issue by thomasnal** [fotinakis/swagger-blocks#56]
Hi,

I am worried I can't find a way how to reference parameters defined on Swagger object on swagger path level. Perhaps it doesn't work? For example, I would expect following to work,

```ruby
swagger_root do
  parameter :name => 'my_param' do
    key :default, 'Awesome value'
  end
end

swagger_path '/my_operation' do
  parameter :'$ref', '#/parameters/my_param'
end
```

But it doesn't. For the most comfortable use I would expect swagger-blocks allows to use it in the following way, the same as the tags work, that is

```ruby
swagger_path '/my_operation' do
  key :parameters, ['my_param']
end
```

Anyone?

**Comment by littlemichu** [comment]
What I did was:

Swagger root:
`
swagger_root do
  parameter :idParam do
    key :name, :id
    key :in, :query
    key :description, 'ID for requested resource'
    key :required, true
    key :type, :string
  end
end
`

Swagger Path:
`
swagger_path '/my_operation do
  parameter do
    key '$ref', '#/parameters/idParam'
  end
end
`

Hope that works for you!

**Comment by fotinakis** [comment]
Yup, what @littlemichu said! :)

**Comment by thomasnal** [comment]
Thanks
