### ISSUE TITLE
Handling multiline string

### ISSUE THREAD

**Issue by thomasnal** [fotinakis/swagger-blocks#57]
Hi,

I see the swagger-blocks makes difference in styling of the API description section depending if I provide single line vs multiline string.

In Swagger YAML if I use,
```yaml
info:
  description: |
    Hello
```
It produces expected description section in default styling. In swagger-blocks, doing it following way,
```ruby
swagger_root do
  info do
    key :description, <<-EOS
      Hello
    end
  end
end
```
produces the description section with its content wrapped in `<pre>` tag (visually a yellow box). Any idea how to make the blocks to produce multiline description not wrapping it in `<pre>` tag, same as Swagger does?

**Comment by fotinakis** [comment]
Swagger is probably Markdown-formatting that field or something, so the whitespace at the beginning of the line turns into a `<pre>`. You need to strip the whitespace from the heredoc, which is just a Ruby question. See http://stackoverflow.com/questions/3772864/how-do-i-remove-leading-whitespace-chars-from-ruby-heredoc for different techniques.

**Comment by thomasnal** [comment]
Nice. That works to remove the <pre> tag.

Though my original need is to send multiple lines to swagger. Writing multiline heredoc now ignores new lines. Sending explicit \n in heredoc or in string gets ignored too. How can I then send a new line from the block description down to swagger?
