### ISSUE TITLE
Can't load swagger paths from a module to the controller

### ISSUE THREAD

**Issue by tonatiuh** [fotinakis/swagger-blocks#58]
I want to load the swagger specifications from a module so that in my controller I can just include such module (that way my controller remains "clean").

I'm trying to make this work with a code alike the one below:

```ruby
class MyController < ApplicationController
  include Swagger::Blocks
  include Swagger::MyControllerDefinition
end

module Swagger
  module MyControllerDefinition
    
    def self.include(base)
      swagger_path '/v1/my_controller' do
        operation :post do
          parameter name: :the_parameter,
                            in: :query,
                            required: true,
                            type: :string
          
          response 200 do
            key :description, 'Successfully executed'
          end
        end
      end
    end
    
  end
end
```

However, that isn't working (when I load the /apidocs no path appears). On the other hand, if I declare the `swagger_path` directly in MyController then it works. 

Am I missing something or is there a specific way to tell swagger-blocks to load the definition from a module?

Thanks in advance.

**Comment by fotinakis** [comment]
In Ruby, `include` only pulls in instance methods, I think you need to `extend` as well in order to pull in the class methods, but I'm not sure exactly what the exact form is.

You can see how we do this in swagger itself here:
https://github.com/fotinakis/swagger-blocks/blob/ed779b7d136e9fc2ebabdd00b37dd33e193f009d/lib/swagger/blocks.rb#L14

Going to close this because this is more of a Ruby question than swagger-blocks itself. If anyone else sees this and has ideas, please share!

**Comment by tonatiuh** [comment]
Thanks!

I checked the link you shared.
Here is what I needed to make my code work: 1) I had a typo, instead of `def self.include(base)` it is `def self.included(base)` 2) I wasn't calling `swagger_path` for the base.

This is the how the code in the module ended up:

```ruby
module Swagger
  module MyControllerDefinition

    def self.included(base)
      base.send(:swagger_path, '/v1/my_controller') do
        operation :post do
          parameter name: :the_parameter,
                            in: :query,
                            required: true,
                            type: :string

          response 200 do
            key :description, 'Successfully executed'
          end
        end
      end
    end

  end
end
```

**Comment by fotinakis** [comment]
👍
