### ISSUE TITLE
Authentication and 'Try it out'

### ISSUE THREAD

**Issue by artjomjuferov** [fotinakis/swagger-blocks#62]
Hi,
There is auth devise in the app and before_filter :authenticate_user! is applied to the action which I want to achieve by 'Try it out'. Is it possible to authenticate before calling 'Try it out'? 
Many thanks.

**Comment by fotinakis** [comment]
I think you are asking a question about Swagger UI, which is not this project. Please see https://github.com/fotinakis/swagger-blocks#filing-issues
