### ISSUE TITLE
Parameter references aren't working properly (v2.0)

### ISSUE THREAD

**Issue by seandilda** [fotinakis/swagger-blocks#64]
The 2.0 spec allows you to reuse parameters.
The first step is to define the reusable parameter in the root - swagger blocks has a parameter method in swagger_root that works well for this.
The second step is to specify the parameter using a ref, something like: 
parameter('$ref' => 'reused_parameter')

In the json, this produces a reference to '#/definitions/reused_parameter'  However, https://github.com/OAI/OpenAPI-Specification/blob/master/guidelines/REUSE.md wants this to be '#/parameters/reused_parameter'

For now I can get around this by using:
parameters('$ref' => '#/parameters/reused_parameter')
but it would be nice if swagger blocks just handled this.

From looking at the code, it looks like there might be a similar issue with reusing responses.

**Comment by fotinakis** [comment]
Release in swagger-blocks v1.4.0.
