### ISSUE TITLE
json context

### ISSUE THREAD

**Issue by JensC** [fotinakis/swagger-blocks#65]
Hi,
I am pretty new to swagger and swagger blocks and this might not be an issue after all - so I hope that you do not get too angry with me.
I am using a parameter definition in swagger-blocks for a Rails api like that:
```
  swagger_path '/users/password' do
    operation :post do
      key :description, 'Request an rest password email.'
      key :tags, ['Reset Password']
      key :operationId, 'create'

      parameter do
        key :name, :user
        key :in, :body
        key :description, 'E-Mail address'
        key :type, :object
        schema do
          key :'$ref', :EmailParams
        end
      end
...
  swagger_schema :EmailParams do
    key :required, [:email]
    property :email do
      key :type, :string
      key :description, 'E-Mail address'
    end
  end

```
Next I am using swagger-ui to create a POST and I get:
```
Started POST "/api/v1/users/password" for ::1 at 2016-08-05 13:42:57 +0200
Processing by Api::V1::PasswordsController#create as JSON
  Parameters: {"email"=>"string", "password"=>{"email"=>"string"}}
```
However I need to have
```
  Parameters: {"email"=>"string", "user"=>{"email"=>"string"}}
```
I did not find any way to accomplish that. Am I doing something wrong or did I forgot any setting??
Thanks in advance

**Comment by fotinakis** [comment]
Hello! Unfortunately I'm not going to be much help for this question as it relates to the swagger spec itself and not swagger-blocks. There are other great places that can help you out including the Swagger community forum and others. Check out our section on Filing Issues for more info: https://github.com/fotinakis/swagger-blocks#filing-issues
