### ISSUE TITLE
Private methods/parameters

### ISSUE THREAD

**Issue by ayudemura** [fotinakis/swagger-blocks#69]
Is there way to flag to hide certain methods/parameters when building root json?

**Comment by fotinakis** [comment]
Is this a part of the Swagger spec, or something you'd like swagger-blocks to do natively? You can always write a wrapper method around build_root_json to manually modify the data based on other factors — https://github.com/fotinakis/swagger-blocks#overriding-attributes

**Comment by ayudemura** [comment]
Rather latter, I think.
For instance,
``` ruby
swagger_path '/something/foo' do
    operation :get do
      key :description, 'something foo'
      key :operationId, 'findSomethingFoo'
      key :tags, [
        'something'
      ]
   end
end
swagger_path '/something/bar' do
    operation :get do
      key :description, 'something bar'
      key :operationId, 'findSomethingBar'
      key :tags, [
        'something'
      ]
   end
end
```
If `/something/bar` is private (internal) endpoint, it would be nice to be able to create json object of public apis vs. private apis (public + private).  Can override do such thing?

**Comment by ayudemura** [comment]
I am closing it because this can't be done with current design.  I got workaround.
