### ISSUE TITLE
Swagger 2.0

### ISSUE THREAD

**Issue by ali-graham** [fotinakis/swagger-blocks#7]
Has there been any work done towards upgrading `swagger-blocks` to support generating Swagger v2-compliant definitions?

https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md
https://github.com/swagger-api/swagger-spec/wiki/Swagger-1.2-to-2.0-Migration-Guide

I can probably spend some time on this shortly, but if anyone has something I'd rather build on that than go it alone.

**Comment by fotinakis** [comment]
Hey @ali-graham, I've planned to support Swagger 2.0 just haven't worked on it yet. Glad to hear there is interest! Is there a particular feature of 2.0 that you want? My plan is to support 100% of the spec like with 1.2, just curious.

The internal design of swagger-blocks will make supporting 2.0 pretty straightforward—I'll have some time in the next two weeks to look into this, or I'm happy to work through a PR with you if you get to it first.

**Comment by ali-graham** [comment]
Hi Mike, I'm looking at describing an API which I'll attempt to have conforming to [JSONAPI](http://jsonapi.org/) v1 when that's released, and I'll probably write another gem depending on `swagger-blocks` to provide common JSONAPI patterns to implementors.

There were a few things in Swagger v2 that caught my eye, after getting some basics implemented using `swagger-blocks` and Swagger v1.2 -- maps as model properties, and `format` as an open-ended property string are a couple that will cut down on the need for extra work or contextual documentation.

Yeah, the internal design is fairly clear, it should be possible to split out various bits depending on the spec version at the various points it differs, plus there will be a few global context parts as well. I should get some time in the next couple of days to have a try, I'll update this issue once I have...

**Comment by ali-graham** [comment]
As is always the way, some of the time has been taken up by other work, but I've started on a separate implementation in https://github.com/ali-graham/swagger-blocks/tree/7_swagger_v2 ; I've not touched the original code as I want to get something working with the new data structures first, then work out how to get one class supporting both types cleanly.

So far it only handles the cut-down v2 partial spec that I'm slowly adding to and testing against, so it's by no means complete. Comments have been cleaned up, some code is commented out and not handled, etc. Where the spec has changed I've tried to use similar internal conventions to mirror the new structures.

**Comment by audionerd** [comment]
+1 to this. It'd be great to see [Security Definitions](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#securityDefinitionsObject) implemented.

**Comment by ali-graham** [comment]
I have most of it done and merged back in as a single file (minus a few of the more complex parts of the spec, e.g. the JSON-Schema stuff), but there are probably a few points needing discussion. (Current work hasn't been pushed up to Github yet, I need to fix some tests and add a few comments, but I should have a PR within the next day or so, and we can work out what to do then.)

**Comment by fotinakis** [comment]
Great! I definitely want to make sure it is a single file / clear interface for implementing either spec version from the same gem, so I'm excited to see what you've come up with and work through any feedback I might have. Thanks for going through the effort! Feel free to send over a PR whenever, even if it's not 100% I can start getting you some early feedback.

**Comment by ali-graham** [comment]
https://github.com/fotinakis/swagger-blocks/pull/8

Not 100%, and needs proper tests, but core structural stuff should be possible to build up with this.

**Comment by jlehman** [comment]
+1 for this as well

**Comment by fotinakis** [comment]
For those following this, we've made good progress on Swagger 2.0 support in swagger-blocks thanks to @ali-graham's work and plan to have an official release soon, or you can manually grab the [https://github.com/fotinakis/swagger-blocks/tree/7_swagger_v2](7_swagger_v2 branch).

**Comment by fotinakis** [comment]
Released v1.1 gem of swagger-blocks with support for Swagger 2.0. Thanks all!

**Comment by audionerd** [comment]
:+1:
