### ISSUE TITLE
key :host, request.host fails

### ISSUE THREAD

**Issue by JohnSmall** [fotinakis/swagger-blocks#73]
In the example the for the swagger_root block we get

`key :host, 'some_hard_coded_host_name`

which is obviously not much use during development, or if you have staging and production servers with different host names. 

I'd like to be able to write

`key :host, request.host`

but if I try that I get:- 

> undefined local variable or method `request' for #<Swagger::Blocks::RootNode:0x007fd43b1bf4b0>

It seems that all the normal methods you expect to be available inside a controller aren't available inside the swagger_root block.

Is there are deliberate reason for this? Is it something I can fix and send you a PR?

**Comment by fotinakis** [comment]
Swagger definitions are made at the module level, not at the instance level, so you do not have access to instance variables like `request`. You can use other things, like `Rails.env.production?` to do something like `key :host, Rails.env.production? ? 'production.example.com' : 'localhost'` (untested).
