### ISSUE TITLE
How to include controllers in <app_root>/app/controllers/api/v1

### ISSUE THREAD

**Issue by nextofsearch** [fotinakis/swagger-blocks#82]
Hi,

I am trying to separate controllers and put them into different directory by version numbers
For example, v1 of carts_controller resides in <app_root>/app/controllers/api/v1/carts_controller.rb

How should I input this controller in SWAGGERED_CLASSES?
SWAGGERED_CLASSES = [ ?? ]

**Comment by fotinakis** [comment]
Just use the full class path including module names, like:

```ruby
SWAGGERED_CLASSES = [
  Api::V1::CartsController,
  Api::V1::FooController,
]
```

**Comment by nextofsearch** [comment]
@fotinakis Thank you!
