### ISSUE TITLE
basePath to "/"

### ISSUE THREAD

**Issue by davidesantangelo** [fotinakis/swagger-blocks#87]
there is a way to specify basePath as root path "/"?

Thanks

**Comment by fotinakis** [comment]
This needs way more info. Have you tried something? What didn't work? What did you expect to happen?

**Comment by davidesantangelo** [comment]
i work on rails mutlitenant API that is not under /api folder because is only an API ex api.domain.com.
I want all requests in this way

http://api.domain.com/:tenant/v1/request

when i try to set base_path: "/" doc UI not work.

**Comment by madakopihub** [comment]
hi @davidesantangelo , i have some case with you. How you resolve it?
