### ISSUE TITLE
Generating Swagger-Blocks based on JSON response?

### ISSUE THREAD

**Issue by ezuk** [fotinakis/swagger-blocks#92]
Hi there,

Can I somehow feed Swagger Blocks (or an associated tool) with a JSON dump of my server's response, and have it magically generate the Ruby for me?

i.e, document backwards -- docs last, based on the response I already have.

**Comment by jodigiordano** [comment]
First of all, awesome work on ErgoDox EZ ;)

I am not affiliated with this project (I only use it) but I understand what you want to achieve.
To support this, you need to code the part that translate your JSON dump to Swagger::Blocks definitions.
It would be some kind of _API documentation generator by examples_ where you feed JSON examples (route, method, authentication, request, response) and the documentation is produced.
This approach has a lot of challenges and drawbacks, way out of scope of this project IMO.

I used this project for a new API so for me, what would be useful is a DSL on top of Swagger::Blocks and other libs so I only have to define once my API and then:

* Controllers are produced automatically (I use Rails controllers).
* Views are produced automatically (I use JBuilder).
* Tests are produced automatically (I use RSpec).
* Documentation is produced automatically (Swagger::Blocks).

That would save me a lot of boilerplate code.
If you're in the same situation, you could try [Grape](https://github.com/ruby-grape/grape) and [Grape-Swagger](https://github.com/ruby-grape/grape-swagger).

Cheers!

**Comment by fotinakis** [comment]
I like the ideas here but this issue is definitely out of scope of this project and my limited time in maintaining it. Going to close this as wontfix to keep things clean, but please feel free to comment if any fruitful discussions come up.

**Comment by ezuk** [comment]
Thank you @jodigiordano! Will explore in that direction next time I need Swagger. And thanks for your kind words re the ErgoDox EZ! :) And thanks @fotinakis as well, totally agree with `wontfix`.
